
[env]
LANG = "en_US.UTF-8"
TERM = "xterm-256color"

[font]
size = 9
builtin_box_drawing = true

[font.bold]
family = "terminal-font"
style = "Bold"

[font.italic]
family = "terminal-font"
style = "Italic"

[font.normal]
family = "terminal-font"
style = "Regular"

[window.padding]
x = 4

[general]
import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[terminal]

[terminal.shell]
program = "/usr/bin/tmux"
